In [260]:
from bs4 import BeautifulSoup

multiple pages data collection

In [311]:
# 50 pages read
soup_pages = []
for i in range(1,51):
    with open(f"htmls/page{i}.html",'r',encoding='utf-8') as f:
        cont = f.read()
        soup_ = BeautifulSoup(cont,"html.parser")
        soup_pages.append(soup_)

#extract all articals tag form (books)
artical_pages = []

for soup in soup_pages:
    articles = soup.select("article")
    artical_pages.extend(articles)

# extract title , ptice and rating
# multiple pages items
items = []
for artical in artical_pages:
    title = artical.find("h3").find("a")['title']
    price = artical.select_one("p.price_color").text.split("£")[1]
    rating_element = artical.select_one("p.star-rating")
    rating = rating_element['class'][1]
    
    # print(classes)
    items.append([title,price,rating])
# create a dataframe
df = pd.DataFrame(items,columns=["Book Title","Price","Rating"])

In [313]:
df.to_csv("data.csv",index=False)


single page read

In [294]:
import pandas as pd
from bs4 import BeautifulSoup



# single file read
with open("htmls/page1.html","r") as f:
    content = f.read()

# single page
articals = soup.select("article.product_pod")

# single page
soup = BeautifulSoup(content,"html.parser")

# single page


# single page
items = []
for artical in articals:
    title = artical.find("h3").find("a")['title']
    price = artical.select_one("p.price_color").text.split("£")[1]
    rating_element = artical.select_one("p.star-rating")
    rating = rating_element['class'][1]
    
    # print(classes)
    items.append([title,price,rating])

# print the Dataframe
df = pd.DataFrame(items,columns=["Book Title","Price","Rating"])
df

                                           Book Title  Price Rating
0                                A Light in the Attic  51.77  Three
1                                  Tipping the Velvet  53.74    One
2                                          Soumission  50.10    One
3                                       Sharp Objects  47.82   Four
4               Sapiens: A Brief History of Humankind  54.23   Five
5                                     The Requiem Red  22.65    One
6   The Dirty Little Secrets of Getting Your Dream...  33.34   Four
7   The Coming Woman: A Novel Based on the Life of...  17.93  Three
8   The Boys in the Boat: Nine Americans and Their...  22.60   Four
9                                     The Black Maria  52.15    One
10     Starving Hearts (Triangular Trade Trilogy, #1)  13.99    Two
11                              Shakespeare's Sonnets  20.66   Four
12                                        Set Me Free  17.46   Five
13  Scott Pilgrim's Precious Little Life (Scott Pi...  52.29   Five
14                          Rip it Up and Start Again  35.02   Five
15  Our Band Could Be Your Life: Scenes from the A...  57.25  Three
16                                               Olio  23.88    One
17  Mesaerion: The Best Science Fiction Stories 18...  37.59    One
18                       Libertarianism for Beginners  51.33    Two
19                            It's Only the Himalayas  45.17    Two

In [291]:
df.to_csv("data.csv",index=False)