In [17]:
import pandas as pd

In [47]:
df = pd.read_csv("data.csv")
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050.0,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565.0,6.0
2,Aamir Khan,Dangal,2016,Biography,2024.0,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431.0,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585.0,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111.0,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180.0,7.5
7,Hrithik Roshan,War,2019,Action,475.0,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318.0,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266.0,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201.0,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342.0,8.2
12,bhimashankar,trader,2025,action,NaN,9.0

In [53]:
df.query("Year > 2019 and IMDb > 5")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050.0,7.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431.0,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266.0,5.9
12,bhimashankar,trader,2025,action,NaN,9.0

In [57]:
df.at[12,"Actor"] = "Bhima"

In [59]:
df.iloc[1,2]

2017

In [61]:
df.loc[12]

Actor                    Bhima
Film                    trader
Year                      2025
Genre                   action
BoxOffice(INR Crore)       NaN
IMDb                       9.0
Name: 12, dtype: object

In [63]:
df.at[0,"Actor"]

'Shah Rukh Khan'

In [45]:
df[(df['IMDb']>6) | (df["Year"]>2018)]

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050.0,7.2
2,Aamir Khan,Dangal,2016,Biography,2024.0,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431.0,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585.0,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111.0,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180.0,7.5
7,Hrithik Roshan,War,2019,Action,475.0,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318.0,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266.0,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201.0,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342.0,8.2
12,Bhima,trader,2025,action,NaN,9.0

In [ ]:
24+18+8+9

In [ ]:
127-59

In [105]:
df = df[["Actor","IMDb"]]

In [107]:
df

                 Actor  IMDb
0              shubham   7.2
1          Salman Khan   6.0
2           Aamir Khan   8.4
3        Ranbir Kapoor   5.6
4        Ranveer Singh   7.0
5   Ayushmann Khurrana   8.3
6        Rajkummar Rao   7.5
7       Hrithik Roshan   6.5
8         Akshay Kumar   7.0
9        Kartik Aaryan   5.9
10        Varun Dhawan   6.1
11       Vicky Kaushal   8.2

In [108]:
df.loc[0,"Actor"] = "shubham"
df

                 Actor  IMDb
0              shubham   7.2
1          Salman Khan   6.0
2           Aamir Khan   8.4
3        Ranbir Kapoor   5.6
4        Ranveer Singh   7.0
5   Ayushmann Khurrana   8.3
6        Rajkummar Rao   7.5
7       Hrithik Roshan   6.5
8         Akshay Kumar   7.0
9        Kartik Aaryan   5.9
10        Varun Dhawan   6.1
11       Vicky Kaushal   8.2

In [98]:
df

                 Actor  IMDb (0, Actor)
0              shubham   7.2    shubham
1          Salman Khan   6.0    shubham
2           Aamir Khan   8.4    shubham
3        Ranbir Kapoor   5.6    shubham
4        Ranveer Singh   7.0    shubham
5   Ayushmann Khurrana   8.3    shubham
6        Rajkummar Rao   7.5    shubham
7       Hrithik Roshan   6.5    shubham
8         Akshay Kumar   7.0    shubham
9        Kartik Aaryan   5.9    shubham
10        Varun Dhawan   6.1    shubham
11       Vicky Kaushal   8.2    shubham